server:
  port: 12301
  contextPath: /web-shop
#  session:
#    cookie:
#      name: JSESSIONID
#      path: /
#      domain: .i-zhiliao.com
spring:
  datasource:
    url: jdbc:mysql://10.0.0.104:3306/zldb?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: zldb1314!#!$
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    minActive: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  thymeleaf: 
    prefix: classpath:/views/
    #content-type: text/html
    #suffix: .html
    #mode: HTML5
    #encoding: UTF-8
    # set to false for hot refresh
    #cache: true
  redis: 
    timeout: 3000
    cluster:
       nodes: 10.0.0.106:7111,10.0.0.103:7112,10.0.0.101:7113
       connection-timeout: 1000
       soTimeout: 3000
       max-attempts: 5
       password: 
       max-redirects: 2
    pool:
       max-total: 1024
       max-active: 8
       max-idle: 8
       max-wait: -1
       min-idle: 0
       block-when-exhausted: true
       max-wait-millis: 3000
       test-on-borrow: false
       test-on-return: false
       test-while-idle: true
       minEvictableIdleTimeMillis: 60000
       timeBetweenEvictionRunsMillis: 60000
       numTestsPerEvictionRun: 1
  dubbo:
    application:
      id: zl-web-shop
      name: zl-web-shop
    protocol:
      name: dubbo
      host:
      port: 20880
      accepts: 1000
    consumer:
      check: false
    registry:
      address: zookeeper://10.0.0.103:12811?backup=10.0.0.106:12812,10.0.0.101:12813
  rocketmq:
    groupName: zlqf_shop_group
    namesrvAddr: 10.0.0.101:9876
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2
    maxMessageSize: 4096
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  type-aliases-package: com.ebeijia.zl.*.dao.**.domain
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:conf/logback-ecom.xml

#锁定短信验证码
sms:
  debug: false

#分页插件
pagehelper:
  reasonable: false
  supportMethodsArguments: true
  params: count=countSql

#相关URL
weixin:
  api:
    code: http://10.0.0.106:15001/web-user/w/getOpenId
    userinfo: http://10.0.0.106:15001/web-user/w/getOpenId
phone:
  api:
    charge: http://10.0.0.103:17001/web-api/api/recharge/mobile/payment
    chargeCallback: http://10.0.0.103:17001/web-shop/supply/phone/charge/callback233
