server:
  port: 11001
  contextPath: /oms
spring:
  mvc:
    view: 
      prefix: /WEB-INF/views/
      suffix: .jsp
      #view-name: '*'
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
  http:
      multipart:
        maxFileSize: 300MB
        maxRequestSize: 300MB
  datasource:
    url: jdbc:mysql://10.0.0.104:3306/zldb?allowMultiQueries=true
    username: root
    password: zldb1314!#!$
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    timeout: 3000
    cluster:
       nodes: 10.0.0.106:7111,10.0.0.103:7112,10.0.0.101:7113,10.0.0.101:7114,10.0.0.106:7115,10.0.0.103:7116
       connection-timeout: 1000
       soTimeout: 3000
       max-attempts: 5
       password:
       max-redirects: 2
    pool:
       max-total: 1024
       max-active: 8
       max-idle: 8
       max-wait: -1
       min-idle: 0
       block-when-exhausted: true
       max-wait-millis: 3000
       test-on-borrow: false
       test-on-return: false
       test-while-idle: true
       minEvictableIdleTimeMillis: 60000
       timeBetweenEvictionRunsMillis: 60000
       numTestsPerEvictionRun: 1
  mq:
    brokerURL: failover:(tcp://10.0.0.101:9876)?randomize=false
    #username: admin
    #password: admin
    pool:
      max-connections: 50
  dubbo:
    application:
      name: zl-web-oms
    consumer:
      check: false
    registry:
      address: zookeeper://10.0.0.101:12813?backup=10.0.0.103:12811,10.0.0.106:12812
mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location: classpath:conf/mybatis-config.xml
logging:
  config: classpath:conf/logback-oms.xml
#FTP服务器连接
ftpClient:
  connect:
    server: 10.0.0.106
    port: 21
    username: app_img
    password: app_img
    separator: /
IMG_SERVER: http://img.i-zhiliao.com
FILE_UPLAOD_PATH: /imgfile
FILE_UPLAOD_SEPARATOR: /
FILE_NEW_PATH: /oms/

IMG_PATH: /data/app/app_oms/images/
#模板下载路径
EXCEL_OPEN_ACCOUNT: /WEB-INF/excel/batchOpenAccount.xlsx
EXCEL_RECHARGE_ACCOUNT: /WEB-INF/excel/batchRecharge.xlsx

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql