server:
  port: 10202
  contextPath: /web-mcht
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  config-location: classpath:conf/mybatis-config.xml
logging:
  config: classpath:conf/logback-mcht.xml
spring:
  datasource:
    url: jdbc:mysql://10.0.0.104:3306/zldb?allowMultiQueries=true
    username: root
    password: zldb1314!#!$
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    minActive: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  redis:
    timeout: 3000
    cluster:
       nodes: 10.0.0.106:7111,10.0.0.103:7112,10.0.0.101:7113,10.0.0.101:7114,10.0.0.106:7115,10.0.0.103:7116
       connection-timeout: 1000
       soTimeout: 3000
       max-attempts: 5
       password:
       max-redirects: 2
    pool:
       max-total: 1024
       max-active: 8
       max-idle: 8
       max-wait: -1
       min-idle: 0
       block-when-exhausted: true
       max-wait-millis: 3000
       test-on-borrow: false
       test-on-return: false
       test-while-idle: true
       minEvictableIdleTimeMillis: 60000
       timeBetweenEvictionRunsMillis: 60000
       numTestsPerEvictionRun: 1
  rocketmq:
    groupName: zlqf_mcht_group
    namesrvAddr: 10.0.0.101:9876
    sendMsgTimeout: 3000
    retryTimesWhenSendFailed: 2
    maxMessageSize: 4096
    consumeThreadMin: 20
    consumeThreadMax: 64
    consumeMessageBatchMaxSize: 1
  dubbo:
    application:
      name: zl-service-mcht
    protocol:
      name: dubbo
      host:
      port: 20881
      accepts: 1000
    provider:
      id: provider_zl-service-mcht
      timeout: 2000
      delay: -1
    consumer:
        check: false
    registry:
      address: zookeeper://10.0.0.103:12811?backup=10.0.0.106:12812,10.0.0.101:12813