server:
  port: 10202
  contextPath: /mcht
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  config-location: classpath:conf/mybatis-config.xml
logging:
  config: classpath:conf/logback-mcht.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.2.110:3306/zldb_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    minActive: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false

  redis: 
    timeout: 3000
    cluster:
       nodes: 192.168.2.110:7111,192.168.2.110:7112,192.168.2.110:7113,192.168.2.110:7114,192.168.2.110:7115,192.168.2.110:7116
       connection-timeout: 1000
       soTimeout: 3000
       max-attempts: 5
       password: 
       max-redirects: 2
    pool:
       max-total: 1024
       max-active: 8
       max-idle: 8
       max-wait: -1
       min-idle: 0
       block-when-exhausted: true
       max-wait-millis: 3000
       test-on-borrow: false
       test-on-return: false
       test-while-idle: true
       minEvictableIdleTimeMillis: 60000
       timeBetweenEvictionRunsMillis: 60000
       numTestsPerEvictionRun: 1
  rocketmq:
    name-server-address: 192.168.2.110:9876
    producer-group: zlqf_group
    send-msg-timeout: 5000
  dubbo:
    application:
      name: zl-service-mcht
    protocol:
      name: dubbo
      port: 20881
      accepts: 1000
    provider:
      id: provider_zl-service-mcht
      timeout: 2000
      delay: -1
    registry:
      address: zookeeper://127.0.0.1:2181