spring:
  profiles: 
    active: test
quartz:
  cronExpression:
    dictBiz: 0 0/5 * * * ?
    jsToken: 0 0/5 * * * ?
    accessToken: 0 0/5 * * * ?
    teleRecharge: 0 0/5 * * * ?
    billingType: 0 0/5 * * * ?