server:
  port: 10201
  contextPath: /itf

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  config-location: classpath:conf/mybatis-config.xml
logging:
  config: classpath:conf/logback-account.xml

spring:
  datasource:
    url: jdbc:mysql://192.168.2.110:3306/zldb_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  dubbo:
    application:
      name: zl-service-account
    protocol:
      name: dubbo
      port: 20880
      accepts: 1000
    provider:
      id: provider_zl-service-account
      timeout: 2000
      delay: -1
    registry:
      address: zookeeper://192.168.2.110:2181?backup=192.168.2.110:2182,192.168.2.110:2183