server:
  port: 10201
  contextPath: /itf
session:
  store-type: redis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  config-location: classpath:conf/mybatis-config.xml
logging:
  config: classpath:conf/logback-account.xml
spring:
  datasource:
    url: jdbc:mysql://192.168.2.110:3306/zldb_test
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    minActive: 1
    maxActive: 20
    initialSize: 1
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  dubbo:
    application:
      name: zl-service-account
    protocol:
      name: dubbo
      host: 192.168.2.223
      port: 20880
      accepts: 1000
    provider:
      id: provider_zl-service-account
      timeout: 2000
      delay: -1
    registry:
      address: zookeeper://127.0.0.1:2181
withdraw:
  yfb:
    publicKeyIndex: 0001
    publicKeyString: 
    merchantNo: 70235957
    productCode: 01070000042
    goodsType: 290054
    privateKeyUrl: D:/app_itf/config/private.key
    bathWithdrawUrl: https://wag.yifubao.com/epps-wag/withdraw.htm
    yfbNotifyUrl: http://zlqfwebapi.free.idcfengye.com/web-api/api/withdraw/suning-yfb/notify